image:
  file: .gitpod.Dockerfile

tasks:
  - command: 'echo Hello!'

ports:
# Because GitPod's auth proxy will only work through the browser, but Hasura needs 
# to ping the server from the CLI, we need to make this port public.
  - port: 5000
    visibility: public
